  /**
   * Tests that {@link #expectThrows} behaves correctly when the Runnable does not throw (an
   * instance of a subclass of) the expected Exception type: by throwing an assertion to <code>FAIL
   * </code> the test.
   */
  public void testFail() {
    final AtomicBoolean ran = new AtomicBoolean(false);
    AssertionError caught = null;
    try {
      final IOException returned =
          expectThrows(
              IOException.class,
              () -> {
                ran.getAndSet(true);
              });
      fail("must not complete"); // NOTE: we don't use expectThrows to test expectThrows
    } catch (AssertionError ae) {
      caught = ae;
    }
    assertTrue(ran.get());
    assertNotNull(caught);
    assertEquals("Expected exception IOException but no exception was thrown", caught.getMessage());
  }

