    @Override
    public void eval(MockDirectoryWrapper dir) throws IOException {

      // Since we throw exc during abort, eg when IW is
      // attempting to delete files, we will leave
      // leftovers:
      dir.setAssertNoUnrefencedFilesOnClose(false);

      if (doFail) {
        if (callStackContainsAnyOf("abort", "finishDocument")
            && false == callStackContainsAnyOf("merge", "close")) {
          if (onlyOnce) {
            doFail = false;
          }
          // System.out.println(Thread.currentThread().getName() + ": now fail");
          // new Throwable().printStackTrace(System.out);
          throw new IOException("now failing on purpose");
        }
      }
    }

