  public void testWrongArity() throws Exception {
    ParseException expected =
        expectThrows(
            ParseException.class,
            () -> {
              JavascriptCompiler.compile("tan()");
              fail();
            });
    assertEquals(
        "Invalid expression 'tan()': Expected (1) arguments for function call (tan), but found (0).",
        expected.getMessage());
    assertEquals(expected.getErrorOffset(), 0);

    expected =
        expectThrows(
            ParseException.class,
            () -> {
              JavascriptCompiler.compile("tan(1, 1)");
            });
    assertTrue(expected.getMessage().contains("arguments for function call"));

    expected =
        expectThrows(
            ParseException.class,
            () -> {
              JavascriptCompiler.compile(" tan()");
            });
    assertEquals(
        "Invalid expression ' tan()': Expected (1) arguments for function call (tan), but found (0).",
        expected.getMessage());
    assertEquals(expected.getErrorOffset(), 1);

    expected =
        expectThrows(
            ParseException.class,
            () -> {
              JavascriptCompiler.compile("1 + tan()");
            });
    assertEquals(
        "Invalid expression '1 + tan()': Expected (1) arguments for function call (tan), but found (0).",
        expected.getMessage());
    assertEquals(expected.getErrorOffset(), 4);
  }

