    @Test
    public void testBackupWithDocsNotSearchable() throws Exception {
        //See SOLR-11616 to see when this issue can be triggered

        assertU(adoc("id", "1"));
        assertU(commit());

        assertU(adoc("id", "2"));

        assertU(commit("openSearcher", "false"));
        assertQ(req("q", "*:*"), "//result[@numFound='1']");
        assertQ(req("q", "id:1"), "//result[@numFound='1']");
        assertQ(req("q", "id:2"), "//result[@numFound='0']");

        //call backup
        final Path locationPath = createBackupLocation();
        final URI locationUri = bootstrapBackupLocation(locationPath);
        final ShardBackupId shardBackupId = new ShardBackupId("shard1", BackupId.zero());

        final CoreContainer cores = h.getCoreContainer();
        cores.getAllowPaths().add(Paths.get(locationUri));
        try (final CoreAdminHandler admin = new CoreAdminHandler(cores)) {
            SolrQueryResponse resp = new SolrQueryResponse();
            admin.handleRequestBody
                    (req(CoreAdminParams.ACTION, CoreAdminParams.CoreAdminAction.BACKUPCORE.toString(),
                            "core", DEFAULT_TEST_COLLECTION_NAME,
                            "location", locationPath.toString(),
                            CoreAdminParams.SHARD_BACKUP_ID, shardBackupId.getIdAsString())
                            , resp);
            assertNull("Backup should have succeeded", resp.getException());
            simpleBackupCheck(locationUri, shardBackupId);
        }
    }

